### ISSUE TITLE
Do we want to redeploy all hubs if we change the deployer in any way?

### ISSUE THREAD

**Issue by consideRatio** [sgibson91/helm-upgrade-decision-logic#2]
Should we really re-deploy all hubs because the deployer has changed?

https://github.com/sgibson91/helm-upgrade-decision-logic/blob/eb68b0b9175f948afb80f86ddc7caa2b7f6be661/helm-upgrade-decision-logic.py#L10-L20

I'm considering the alternative that if we know we have made a change to the deployer that motivates a redeploy of all hubs, because of some magic part of the deployer rather than part of the helm charts and their config, we should manually redeploy the hubs instead.

**Comment by sgibson91** [comment]
I think that should be a decision for the @2i2c-org/tech-team, but I don't think any kind of manual redeploys scales very well

**Comment by consideRatio** [comment]
> I think that should be a decision for the @2i2c-org/tech-team, but I don't think any kind of manual redeploys scales very well

:+1: to considering that as a group.

I think as we do less and less things as part of the deployer with regards to the actual deployments, it is more and more reasonable to not re-deploy all hubs if something has changed in the deployer.

In practice, what change in the deployer script would motivate a redeploy? I think I'm not going to be feeling confident about either decision without better understanding that.

---

Note when I say "manual", I also think of the option of manually pressing a "Run workflow" button in the GitHub UI, as made possible by declaring a `workflow_dispatch` trigger. Supporting this would include some work though, as our workflow logic relies on changes to have been made and us deciding to publish or not depending on such changes.

**Comment by sgibson91** [comment]
One thing we need to know is: when does a change to the deployer equate to a noop on the hubs?

A lot of the PRs I made today, didn't need to trigger redeploys of the hubs since they were touching the logic of reading in files. However, PRs like @GeorgianaElena's work on CILogon, probably would need to trigger a redeploy of hubs (either manually or automatically in CI/CD). What processes can we think to help engineers make that judgment call?

**Comment by yuvipanda** [comment]
I think we should definitely redeploy the hubs whenever the deployer changes, as it's impossible I think to figure out exactly when it needs to be and doesn't need to be. I think the return on investment in getting this logic and getting it 'right' and dealing with exceptions is probably not worth the total time it'll save us.
